#user service will be here



class UserService:
    
    def __init__(self):
        # repo = UserRepository()
        pass
    
    
    def get_all_users(self):
        return {"message": "List of all users geted from user service without repo"}


    def create_user(self):
        return {"message": "User created with the payload sent to the user service via user controller without repo"}


    def get_user_by_id(self, user_id):
        return {"message": f"User with id {user_id} geted by the user service via user controller without repo"}


    def update_user_by_id(self, user_id):
        return {"message": f"User with id {user_id} updated with the payload sent to the user service via user controller without repo"}


    def delete_user_by_id(self, user_id):
        return {"message": f"User with id {user_id} deleted by the user service via user controller without repo"}


    def login_user(self):
        return {"message": "User logged in and token generated by the user service without repo"}