from werkzeug.security import generate_password_hash
from models.user_model import User
from repositories.user_repository import UserRepository
from dtos.user_dto import UserDTO


class UserService:
    
    def __init__(self):
        self.user_repository = UserRepository()
    
    
    def get_all_users(self):
        users = self.user_repository.get_all_users()
        return UserDTO.from_list(users)


    def create_user(self, data):
        hashed_password = generate_password_hash(data.get('password'))
        
        new_user = User(
            username=data.get('username'),
            email=data.get('email'),
            password=hashed_password
        )
        
        saved_user = self.user_repository.save(new_user)
        
        return UserDTO(saved_user).to_json()


    def get_user_by_id(self, user_id):
        user = self.user_repository.get_user_by_id(user_id)
        if not user:
            return None
        return UserDTO(user).to_json()


    def update_user_by_id(self, user_id, data):
        user = self.user_repository.get_user_by_id(user_id)
        if not user:
            return None

        if 'username' in data: user.username = data.get('username')
        if 'email' in data: user.email = data.get('email')
        if 'password' in data: user.password = generate_password_hash(data.get('password'))
        
        return UserDTO(self.user_repository.save(user)).to_json()


    def delete_user_by_id(self, user_id):
        user = self.user_repository.get_user_by_id(user_id)
        if not user:
            return False
        
        self.user_repository.delete(user)
        return True 


    def login_user(self):
        return {"message": "User logged in and token generated by the user service without repo"}
    
    
    def get_user_by_email(self, email):
        user = self.user_repository.get_user_by_email(email)
        return UserDTO(user).to_json() if user else None
    
    
    def check_email_exists(self, email):
        return self.user_repository.get_user_by_email(email) is not None